# Use the latest Cypress image with browsers
FROM cypress/included:latest

# Set the working directory
WORKDIR /e2e

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the test code
COPY . .

# Run Cypress tests
CMD ["npx", "cypress", "run"]
