name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t my-cypress-image -f Dockerfile.cypress .

      - name: Run Cypress tests
        run: |
          docker run \
            --network=host \
            -v $(pwd)/cypress/reports:/e2e/cypress/reports \
            my-cypress-image npx cypress run

      - name: Upload Cypress reports
        uses: actions/upload-artifact@v3
        with:
          name: cypress-reports
          path: cypress/reports
